spring.application.name=Nest-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/nest
spring.datasource.username=tarunkumar
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=MySecretKeyForJWTTokenGenerationAndValidationPurposeThatIsLongEnough12345678901234567890
jwt.expiration=86400000